### ISSUE TITLE
alueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by leandrodlorenzo** [ugurozturk/instabot.pyV2#10]
Hi i have this problem, can you help me?

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "check_status.py", line 3, in <module>
    from .user_info import get_user_info
ValueError: Attempted relative import in non-package

**Comment by joby8** [comment]
yes, i have got the same problem. But i can't help. sorry

**Comment by mmming** [comment]
Have the same issue.(

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

**Comment by viveksb007** [comment]
just goto src directory and remove '.' from every import statement
Like if its "from .user_info import get_user_info" change it to "from user_info import get_user_info"
This would solve import issue.

**Comment by ugurozturk** [comment]
made new commit. Forgotten example.py broke this. And duplicate of #7
