### ISSUE TITLE
when i tries to comment it rices error 

### ISSUE THREAD

**Issue by ayush3298** [ugurozturk/instabot.pyV2#11]
Traceback (most recent call last):
  File "E:\instabot.pyV2-masterv2\example.py", line 79, in <module>
    bot.new_auto_mod()
  File "E:\instabot.pyV2-masterv2\src\instabot.py", line 691, in new_auto_mod
    self.new_auto_mod_comments()
  File "E:\instabot.pyV2-masterv2\src\instabot.py", line 759, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['code']) == False:
KeyError: 'code'
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [y ] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [y ] Searched and checked orher issues about my problem
- [ n] I have errors.log file and i did upload it

Check One 💯 
- [ ] Bug
- [ ] `Feature`
- [ ] Need Help

## What OS ?
windows
### VPS: Is the vps far far away ? Another Country ?
- [ y] VPS: Tried the same code via my local pc

**Comment by ugurozturk** [comment]
fixed. https://github.com/ugurozturk/instabot.pyV2/commit/1aefb0af369beac5d603cbc1255277b661b7f84f

**Comment by ayush3298** [comment]
thank you man
