### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bloggerpact** [ugurozturk/instabot.pyV2#13]
Hey, @unformatt 

I'm getting this error : 

python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "G:\www\Instabot\instabot.pyV2\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "G:\www\Instabot\instabot.pyV2\src\instabot.py", line 696
    min=self.start_at_m), end="\r")
                             ^
SyntaxError: invalid syntax

Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [y ] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [ y] Searched and checked other issues about my problem
- [ y] I have errors.log file and i did upload it

Check One :
- [y ] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
windows
## Python Version ?
Python 2.7.12
### VPS: Is the vps far far away ? Another Country ?
- [ ] VPS: Tried the same code via my local pc

**Comment by ugurozturk** [comment]
@bloggerpact it is happening because python 2x print. Anyway i did fix it. You better use python3. Still it should work via python2 now.
