### ISSUE TITLE
bot stopped working when it came to unfollow users

### ISSUE THREAD

**Issue by joby8** [ugurozturk/instabot.pyV2#14]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [x] Searched and checked orher issues about my problem
- [ ] I have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [x] Need Help

### VPS: Is the vps far far away ? Another Country ? Idk. I'm from Germany
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10

Hey there!
my problem is, that the bot just stopps working when it comes to unfollow users. Last time he stopped working when he tried to unfollow user #4
 I hope you can help me! Thanks in advance!

**Comment by ugurozturk** [comment]
@joby8 did you upgrade this repo ? And Send here error codes.

**Comment by ugurozturk** [comment]
@joby8 i meant are you using via my last commit ? just delete your folder and re-download it. https://github.com/ugurozturk/instabot.pyV2/archive/masterv2.zip

**Comment by joby8** [comment]
@ugurozturk I re-downloaded it and till now it's working, thanks man!
