### ISSUE TITLE
Configuration help 

### ISSUE THREAD

**Issue by lukasz00500** [ugurozturk/instabot.pyV2#15]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [x] Searched and checked orher issues about my problem
- [ ] I have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [x] Need Help

Hello i need help

is there an option for this configuration:

like photo by tag "example_tag" then like 5 photos of this person.
and Again like by tag "example_tag" Then  again like 5 photos from this user

**Comment by ugurozturk** [comment]
@lukasz00500 nope. There is not a feature here. I do only support and develop mod 0. And i wont gonna do that soon.
