### ISSUE TITLE
Like only 48-51 photos when Getting media by one tag

### ISSUE THREAD

**Issue by lukasz00500** [ugurozturk/instabot.pyV2#16]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [x] Searched and checked orher issues about my problem
- [ ] I have errors.log file and i did upload it

Check One :
- [x] Bug
- [ ] Feature
- [ ] Need Help

### VPS: Is the vps far far away ? Another Country ?
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10

Is There limits  to  "bot.like_all_exist_media"
 
![screenshot_20180103-222758](https://user-images.githubusercontent.com/27085533/34540609-80ebaaa2-f0d5-11e7-80bd-0d915cbe90fc.png)

> bot = InstaBot('login', 'password')
> bot.get_media_id_by_tag('python')
> bot.like_all_exist_media(1000)

my bot only likes about 50 photos then receives the message "keep calm - it's alredy liked"
![screenshot_20180103-221327](https://user-images.githubusercontent.com/27085533/34540598-74ed66b4-f0d5-11e7-98e9-e3a21c49ed33.jpg)

**Comment by ugurozturk** [comment]
@lukasz00500 because you are using wrong syntax. please use https://raw.githubusercontent.com/ugurozturk/instabot.pyV2/masterv2/example.py as like this. And use python3 instead python2

**Comment by lukasz00500** [comment]
But i want to use option  to like  1000 photos   from selected tag  one by one so  i need 

> bot.like_all_exist_media(1000) 
How  to add this to this file ?

**Comment by ugurozturk** [comment]
@lukasz00500 it is dangerous by the way. You better use many tags. Still i think you can make like

```
bot = InstaBot(
    login="username",
    password="password",
    like_per_day=1000,
    tag_list=['tag'],
    max_like_for_one_tag=1000,
    follow_per_day=0,
    unfollow_per_day=0
    log_mod=0)
```

**Comment by lukasz00500** [comment]
Yes, but is not it just the upper limit? I mean
it might like 100 photos then it will reset but also can like 5 photos and reset and again like the latest photos

**Comment by ugurozturk** [comment]
@lukasz00500 it is working. I am using it on my android. And no it is not just upper limit. it goes to recent medias of the tag then it tries to like. The "1000" might fails it. So you can test and send here new errors so i can try to fix it.

**Comment by lukasz00500** [comment]
I have python  2 and 3 on my Phone same configuration  and on python  2 work Perfect but on python 3 im getting this
![screenshot_20180103-231659](https://user-images.githubusercontent.com/27085533/34542613-95f0f878-f0dd-11e7-86e9-2005f633ac90.jpg)

**Comment by ugurozturk** [comment]
@lukasz00500 unable to open database file. it is probabby happening because still the python2 is using it. Try to restart your phone then make first go via python3. If it is still gives the error, do backup then delete the follows_db.db file.

**Comment by lukasz00500** [comment]
I know  that  it's tries to like but every time I see "Get media id by tag: "tag"  it will refresh photo list

I want to like  some older  posts from selected tag

**Comment by ugurozturk** [comment]
@lukasz00500 PRs always welcomed. if you find to get older photos from instagram json just open an issue that you found it. Then i will implement it. For now i dont know a way to get the older photos.

**Comment by lukasz00500** [comment]
![screenshot_20180103-234837](https://user-images.githubusercontent.com/27085533/34543355-b1247c20-f0e0-11e7-8712-d9542516994a.jpg)

As you can see it refreshing tag in random moment not after 1000 photos

**Comment by ugurozturk** [comment]
@lukasz00500 1000 is not possible bot can get max 51 photos from recent medias of a tag. And if there is already liked ones it is just removes them. And whenever there is never ones the bot will just likes them. By the way the thing is better in this way. Because you are liking active users by this way. And a lot of person does like recent medias. If you go the older ones then you would say to instagram that you are a bot.

**Comment by lukasz00500** [comment]
Ok this  is the answere I wanted:) so there is no way  to load more  than 51  photos from one tag 
I cant change this limit ?

**Comment by lukasz00500** [comment]
And im getting error after uninstall python 2 and restart The Phone.   
![screenshot_20180104-001615](https://user-images.githubusercontent.com/27085533/34544129-bbd62ba6-f0e4-11e7-8269-8b39cf890867.png)

**Comment by ugurozturk** [comment]
@lukasz00500 did you also delete the file called follows_db.db ?

**Comment by lukasz00500** [comment]
Yes all file deleted

04.01.2018 01:12 "ugurozturk" <notifications@github.com> napisał(a):

**Comment by ugurozturk** [comment]
@lukasz00500 its weird. Im going to try this repo from empty one as you do then. 

1. Deleting all the files qpython/follows_db.db abd qpython/projects3/instabot.pyV2/*
2. Importing clean repo and changing example.py as my wish.
3. Running the code.. Everything working.

So what is different on you ? Perhaps you are not deleted the follows_db.db im saying this twice because the follows_db.db file is not in the repo while using qpython. It does create it to outside folder.

**Comment by lukasz00500** [comment]
Now I deleted all files  whole folder 'qpython' 

Uninstall python 2 and 3 and after fresh start i have even problem  with installing  requests from pip console.  (Before I moved it manually from python 2)
![screenshot_20180104-093325](https://user-images.githubusercontent.com/27085533/34555594-deb53f60-f132-11e7-9fce-1ffd26bcf379.png)

**Comment by ugurozturk** [comment]
@lukasz00500 what android version are you using ?

**Comment by ugurozturk** [comment]
@lukasz00500  http://docs.python-requests.org/en/master/ "The use of Python 3 is highly preferred over Python 2" and the error looks like qpython problem. Not the repos. So you do better finding the error in qpython forums. I do have nothing wrong or non error.
