### ISSUE TITLE
Running two Bot in same Repertory DataBase

### ISSUE THREAD

**Issue by AyoubMarouan** [ugurozturk/instabot.pyV2#17]
I just notice you using database to store activity, running two bot in same repertory do effect the database ?

**Comment by ugurozturk** [comment]
I was using this repo for myself single run but if it is needed i think i can develop it. Lets make feature request. And track this in there.

**Comment by ugurozturk** [comment]
will be tracking in https://github.com/ugurozturk/instabot.pyV2/issues/18
