### ISSUE TITLE
Feature : Two bot at the same time

### ISSUE THREAD

**Issue by ugurozturk** [ugurozturk/instabot.pyV2#18]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

Check One :
- [x] Feature

## Detail
Lets make it possible to run more than one bot at the same time.

**Comment by ugurozturk** [comment]
@AyoubMarouan I made some changes on the branch https://github.com/ugurozturk/instabot.pyV2/tree/more-than-onebot Can you test it ?

**Comment by shubs** [comment]
I tried, it works !

**Comment by ugurozturk** [comment]
Implemented. https://github.com/ugurozturk/instabot.pyV2/commit/1efc086d16e178d2c256b235b86d25e7e55639db

**Comment by ugurozturk** [comment]
@shubs i need feedback about this. I dont use two account at the same time so i have to ask. Is there any trouble about using two account in the same time ?
