### ISSUE TITLE
Last Followed Time

### ISSUE THREAD

**Issue by ugurozturk** [ugurozturk/instabot.pyV2#19]
Check One :
- [x] Feature

Lets track follow time. I made this column before. Also going to use it for new features like "a person how many times can be followed"  and "How much later the person can be unfollowed"

**Comment by zephyrspikie27391** [comment]
Hello,

When following users using example.py, does it auto unfollow the people that it followed only or does it also unfollow people that I followed before using it? 

Not a programmer but I have been using this script for the auto likes and it is great!

**Comment by ugurozturk** [comment]
@zephyrspikie27391 it does only unfollow whose bot did follow.

**Comment by ugurozturk** [comment]
https://github.com/ugurozturk/instabot.pyV2/commit/78ad90f48fa79fa7e4ad7b9deb4538f0766fe0ad
