### ISSUE TITLE
removing already liked medias

### ISSUE THREAD

**Issue by khakh101** [ugurozturk/instabot.pyV2#20]
![help](https://user-images.githubusercontent.com/35112573/34583616-dc90de86-f1b1-11e7-9ba6-7e0cc9d48ad4.PNG)
i've been trying to figure this out for the past hour but the same thing keeps happening how can i fix this

**Comment by ugurozturk** [comment]
@khakh101 https://github.com/ugurozturk/instabot.pyV2/blob/masterv2/ISSUE_TEMPLATE.md
