### ISSUE TITLE
Cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by monanabanana** [ugurozturk/instabot.pyV2#24]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [X] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [X] Searched and checked other issues about my problem
- [X] If have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [X] Need Help

## What OS ?
Android
## Python Version ?
2.0.10
## Is it VPS ?
Yes / No
### VPS: Is the vps far far away ? Another Country ?
Not sure
### VPS: Tried the same code via my local pc
Not sure
## What is your python knowledge vote 0/10
2

Issue:

`05.01.2018_23:53 myuser login success!
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/projects/instabot.pyV2-masterv2/main.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/storage/emulated/0/qpython/projects/instabot.pyV2-masterv2/src/instabot.py", line 222, in _init_
    self.populate_user_blacklist()
  File "/storage/emulated/0/qpython/projects/instabot.pyV2-masterv2/src/instabot.py", line 232, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
1|F8331:/ $`

I know it's a problem with User_Blacklist.
I write a name **user_blacklist = {'name': ''}** and it doesn't work. I remove it, and it works. Can you help me, please? :)

**Comment by ugurozturk** [comment]
@monanabanana python version looks so old. Lets time save via updating python. Please use Python3x. And open a new issue or comment here if the gives still an error.

Also i never tried black_list before and checked original repo and they says it is already broken feature. I would try to fix it if many people asks for it.
