### ISSUE TITLE
logout and stops working

### ISSUE THREAD

**Issue by koeniig2** [ugurozturk/instabot.pyV2#27]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [ ] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [ ] Searched and checked other issues about my problem
- [ ] If have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
MAC / Windows / Linux(detail) / Android
## Python Version ?
2x / 3x
## Is it VPS ?
Yes / No
### VPS: Is the vps far far away ? Another Country ?
Yes / No
- [ ] VPS: Tried the same code via my local pc

**Comment by koeniig2** [comment]
bot stops working after a while... it says Logout..

**Comment by ugurozturk** [comment]
Fill all requirements before sending issues. Or all issues will be closed without reading.

**Comment by koeniig2** [comment]
Fuck your mom
