### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by EightShift** [ugurozturk/instabot.pyV2#33]
Hi
The first day everything was fine.
But on the second day I see this:

![df](https://user-images.githubusercontent.com/35277031/34767414-36e0dce6-f622-11e7-897b-af8fb30a7087.jpg)

And in the Instagram application I see the message "suspicious login attempt" with the location of the login with confirmation of whether I'm logging in.
What to do?

**Comment by ugurozturk** [comment]
@EightShift https://github.com/ugurozturk/instabot.pyV2/blob/masterv2/ISSUE_TEMPLATE.md . "Fill all requirements before sending issues. Or all issues will be closed without reading."
