### ISSUE TITLE
Login error Connection Error

### ISSUE THREAD

**Issue by EightShift** [ugurozturk/instabot.pyV2#34]
Hi
The first day everything was fine.
But on the second day I see this:

![df](https://user-images.githubusercontent.com/35277031/34774121-5d6e5cec-f638-11e7-906f-01cc91fb4494.jpg)

And in the Instagram application I see the message "suspicious login attempt" with the location of the login with confirmation of whether I'm logging in.
What to do?

Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [+] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [+] Searched and checked other issues about my problem
- [-] If have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [+] Need Help

## What OS ?
Windows
## Python Version ?
3x
## Is it VPS ?
No
### VPS: Is the vps far far away ? Another Country ?
-
- [-] VPS: Tried the same code via my local pc

**Comment by ugurozturk** [comment]
@EightShift It didn't happened to me before but i did read in original repo about this. Please read here https://github.com/instabot-py/instabot.py/issues/842 and if you find the solution post here to help others.

**Comment by ugurozturk** [comment]
@EightShift are you using proxy ? or a vpn ?

**Comment by ugurozturk** [comment]
As well it might be problematic via USER_AGENT  or ig numbers. to fix it if you can send me what is your user_agent and ig numbers. 

Alert : dont post here your CSRFToken.

**Comment by gabrielsonoda** [comment]
![sem titulo](https://user-images.githubusercontent.com/32623494/34778503-add7b32e-f604-11e7-80fa-a6a2dd2c485a.jpg)

I'm having a similar problem, yesterday it was working fine.

**Comment by ugurozturk** [comment]
@gabrielsonoda @EightShift  https://github.com/ugurozturk/instabot.pyV2/tree/login_error after this moment use this branch to fix this error. I dont having the problem so you two must be try and send here error.log file.

**Comment by EightShift** [comment]
`Login error! Connection error! {"message": "checkpoint_required", "checkpoint_url": "/challenge/**********/**********/", "lock": false, "status": "fail"}`

Everything works if you run the bot on a new account, .
As with the new and with the old instabot.py

PS: I wonder if it's possible to add a code to the bot that asked for the confirmation code sent by Intsagram. To Instagram realized that the bot - it's really me.

**Comment by ugurozturk** [comment]
@EightShift you said it is not vps and it is windows. And i asked if you are using proxy or vpn. if so just try to login via your browser and do the validation thing. Then the code would run as good as before.

**Comment by EightShift** [comment]
I did that. But nothing has changed. :(

**Comment by EightShift** [comment]
And I'm sorry, I'm a bit stupid. And English is not my native language.

**Comment by ugurozturk** [comment]
@EightShift well i dont have the solution it is about you and your computer. You can make ip reset and browser cache, perhaps it can help you. i will keep this open, if anybody find the solution so.

**Comment by iceman183** [comment]
@EightShift  This has happened to me before as well. Its usually caused by different or new geolocation ip and sometimes Instagram is random with it. Just accept the suspicious login from the Instagram app. 

You should also find if you internet connection has static ip or not.

**Comment by EightShift** [comment]
hm...
I was do [this one](https://support.microsoft.com/en-us/help/299357/how-to-reset-tcp-ip-by-using-the-netshell-utility)
and this one: 
`netsh winsock reset`
`netsh int ip reset %temp%\reset.log`
and it's work!
I, actualy, don't know what exacly help, but it's work.
Don't close the issue for now, please. At least 2 days of test.

**Comment by uchibeke** [comment]
Use the updated  `login_error` branch. If you get the login error, copy the '/challenge/<code>/' from the terminal and append it to `http://instagram.com` i.e `http://instagram.com/challenge/<code>/`. 

Visit that link on your browser and solve the challenge. It will either be confirming that it was you or getting a confirmation code via text/email. Once completed, try the run script again. It should work.

If you get the error again, wait for a few minutes/hours and retry. It will fail again with a challenge. Solve the challenge as shown above and you should be good.

**Comment by kibou80** [comment]
this happened to me too today... and they actually had reset my account password... I updated my password and it's back working again with my new password!

**Comment by ugurozturk** [comment]
please use original repo https://github.com/instabot-py/instabot.py
