### ISSUE TITLE
Except on get_media!

### ISSUE THREAD

**Issue by vocoun** [ugurozturk/instabot.pyV2#37]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [x] Searched and checked other issues about my problem
- [ ] If have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [x] Need Help

## What OS ?
openSUSE Leap 42.3
## Python Version ?
Python 3.4.6
## Is it VPS ?
No
### VPS: Is the vps far far away ? Another Country ?
No
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 3/10

I have got the following error:
10.01.2018_21:34 ZZZZZZZ : Get media id on recent feed 
 10.01.2018 21:34
10.01.2018_21:34 Media in recent feed = 0
10.01.2018_21:34 ======> Get media id by Tag <======
10.01.2018_21:34 XXXXXXX Except on get_media! XXXXXXX
-----------------------------------------------------------
Upss YYYYYY is already in ex user list... 
--------------------------------------------------------------

And I got this message for about thousand times.

**Comment by iceman183** [comment]
Post your example.py and tell us what mode you are using? This seems like a mode different than 0

**Comment by vocoun** [comment]
> Post your example.py and tell us what mode you are using? This seems like a mode different than 0 and also upload a file called errors.log

Unfortunately, my errors.log file seems to be empty. 
Yes. I am using mode 2. Is there any constraints?

example.py :
```

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import time


from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login= 'user_name',
    password= '_password_,
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['android'],
    tag_blacklist=[''],
    user_blacklist={},
    max_like_for_one_tag=13,
    follow_per_day=100,
    follow_time=1 * 60,
    unfollow_per_day=80,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["android is the best", "Amazing!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[''],
    unfollow_whitelist=['']) 
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by iceman183** [comment]
@vocoun So I don't believe @ugurozturk has reworked any of the other modes other than 0 and I always found the other modes to be super buggy from the original repo. Even while reverse engineering, I found it rather confusing and all over so I suggest you stick to mode 0 unless @ugurozturk has something else to share.

As far as unfollowing is concerned, just download the app called unfollowers for instagram if you have an android. It lets see you see all the users who don't follow you back and you can unfollow them in bulk and also add stars to the ones you dont want to so as to keep them.

**Comment by vocoun** [comment]
@iceman183 Ok. I got it. Thanx. Actually, I do not need unfollowers mode much and just think I can choose any mode.

**Comment by ugurozturk** [comment]
@vocoun as @iceman183 said. i didn't edit any of the modes. And i will not edit any of them. Also mode 0 's unfollow protocol is changed from original repo. In this repo we do unfollow from database with random. There will be also possible to do like "unfollow followed person after 2days".
