### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by enriqueg** [ugurozturk/instabot.pyV2#7]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [ x] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [ x] Searched and checked orher issues about my problem
- [ ] I have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ ] Feature
- [ x] Need Help

### VPS: Is the vps far far away ? Another Country ?NO
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10

@ugurozturk
Could you please help me, I got this:
python example.py
Traceback (most recent call last):
File "example.py", line 9, in 
from check_status import check_status
File "/Users/MC/instabot.pyV2-masterv2/src/check_status.py", line 3, in 
from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

**Comment by r1b4z01d** [comment]
I am receiving this same issue with OSX on and Python 2.7.8. I am looking in to it on my side now.

**Comment by ugurozturk** [comment]
@enriqueg @r1b4z01d Sorry, i forgot to delete one line on this repo. in the example.py line 7 

> sys.path.append(os.path.join(sys.path[0], 'src'))

 delete it. i will make new commit for it

**Comment by ugurozturk** [comment]
Closing this issue. do pull then If you having the error again, just comment.
