### ISSUE TITLE
Issue with getting the bot started up

### ISSUE THREAD

**Issue by heydanaye** [ugurozturk/instabot.pyV2#9]
From the first time I've ran the script I've gotten this error message.

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "/Users/Username/Desktop/instabot.pyV2-masterv2/src/check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

I'm running on Mac OSX with python 3.6.4 and the 'Requirements.txt' has already been installed. Please help!

Thank you!

**Comment by neospeed83** [comment]
same here.

**Comment by ugurozturk** [comment]
@heydanaye @neospeed83 check new commit and this is duplicate #7
